// Generated by Wrangler by running `wrangler types`
declare namespace Cloudflare {
	interface Env {
		OAUTH_KV: KVNamespace;
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
		ASSETS: Fetcher;
		LOADER: WorkerLoader;
	}
}
interface Env extends Cloudflare.Env {}
